#!/bin/sh

db=store_db

for i in `psql -U store_user -h postgres $db -t -c "select tablename from pg_tables where schemaname = 'public'"`; do psql -U store_user -h postgres $db -c "drop table if exists $i cascade"; done

for i in `psql -U store_user -h postgres $db -t -c "select relname from pg_class where relkind='S'"`; do psql -U store_user -h postgres $db -c "drop sequence $i"; done
