#!/bin/sh

for i in `psql -h /tmp store_db -t -c "select tablename from pg_tables where schemaname = 'public'"`; do psql -h /tmp store_db -c "drop table if exists $i cascade"; done

for i in `psql -h /tmp store_db -t -c "select relname from pg_class where relkind='S'"`; do psql -h /tmp store_db -c "drop sequence $i"; done
